# 1. Imagen base
FROM node:18

# 2. Crear carpeta de trabajo
WORKDIR /app

# 3. Copiar package.json
COPY package*.json ./

# 4. Instalar dependencias
RUN npm install

# 5. Copiar todo el proyecto
COPY . .

# 6. Exponer puerto
EXPOSE 3000

# 7. Ejecutar la app
CMD ["npm", "start"]